### ISSUE TITLE
Missing SQS import

### ISSUE THREAD

**Issue by erhudy** [covid-alert-ny/covid-green-regional-lambdas#14]
This is on prod-nys-sms:

```
2020-08-28T16:42:36.837-04:00

Copy
2020-08-28T20:42:36.837Z	6698b7e0-6129-5ec8-89aa-e0230f5a1213	ERROR	Invoke Error	
{
    "errorType": "ReferenceError",
    "errorMessage": "sqs is not defined",
    "stack": [
        "ReferenceError: sqs is not defined",
        "    at Runtime.exports.handler (/var/task/sms.js:47:7)",
        "    at process._tickCallback (internal/process/next_tick.js:68:7)"
    ]
}
```

**Comment by aisegfault** [comment]
fixed
