### ISSUE TITLE
SMS lambda errors out for invalid phone number

### ISSUE THREAD

**Issue by erhudy** [covid-alert-ny/covid-green-regional-lambdas#15]
Malformed numbers should not go on the retry queue:

```
2020-08-28T20:42:36.837Z	6698b7e0-6129-5ec8-89aa-e0230f5a1213	ERROR	{ Error: The 'To' number +12121112222 is not a valid phone number.
    at success (/var/task/node_modules/twilio/lib/base/Version.js:135:15)
    at Promise_then_fulfilled (/var/task/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/var/task/node_modules/q/q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (/var/task/node_modules/q/q.js:1229:9)
    at Pending_become_eachMessage_task (/var/task/node_modules/q/q.js:1369:30)
    at RawTask.call (/var/task/node_modules/asap/asap.js:40:19)
    at flush (/var/task/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  status: 400,
  code: 21211,
  moreInfo: 'https://www.twilio.com/docs/errors/21211',
  details: undefined }
```

**Comment by aisegfault** [comment]
fixed
